---
- ros_topic_name: "<namespace>/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "<namespace>/joint_states"
  gz_topic_name: "/world/map/model/drone<drone_number>/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "<namespace>/odometry"
  gz_topic_name: "/model/drone<drone_number>/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "<namespace>/gz/tf"
  gz_topic_name: "/model/drone<drone_number>/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "<namespace>/gz/tf_static"
  gz_topic_name: "/model/drone<drone_number>/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "<namespace>/camera/image"
  gz_topic_name: "/world/map/model/drone<drone_number>/link/tilt_link/sensor/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "<namespace>/camera/camera_info"
  gz_topic_name: "/world/map/model/drone<drone_number>/link/tilt_link/sensor/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "<namespace>/air_pressure"
  gz_topic_name: "/world/map/model/drone<drone_number>/link/base_link/sensor/air_pressure_sensor/air_pressure"
  ros_type_name: "sensor_msgs/msg/FluidPressure"
  gz_type_name: "gz.msgs.FluidPressure"
  direction: GZ_TO_ROS

- ros_topic_name: "<namespace>/imu"
  gz_topic_name: "/world/map/model/drone<drone_number>/link/imu_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "<namespace>/magnetometer"
  gz_topic_name: "/world/map/model/drone<drone_number>/link/base_link/sensor/magnetometer_sensor/magnetometer"
  ros_type_name: "sensor_msgs/msg/MagneticField"
  gz_type_name: "gz.msgs.Magnetometer"
  direction: GZ_TO_ROS

- ros_topic_name: "<namespace>/navsat"
  gz_topic_name: "/world/map/model/drone<drone_number>/link/base_link/sensor/navsat_sensor/navsat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS

- ros_topic_name: "<namespace>/battery"
  gz_topic_name: "/model/drone<drone_number>/battery/lipo_3500mAh/state"
  ros_type_name: "sensor_msgs/msg/BatteryState"
  gz_type_name: "gz.msgs.BatteryState"
  direction: GZ_TO_ROS

- ros_topic_name: "<namespace>/lidar"
  gz_topic_name: "/world/map/model/drone<drone_number>/link/base_scan/sensor/gpu_lidar/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "<namespace>/lidar_points"
  gz_topic_name: "/world/map/model/drone<drone_number>/link/base_scan/sensor/gpu_lidar/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
